[build-system]
requires = ["setuptools >= 46.4.0", "wheel >= 0.34.2", "Cython", "numpy == 1.25.2"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# ../../numpy/meson.build:207:4: ERROR: Problem encountered: No BLAS library detected!
# Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
#skip = [
#    "pp310-manylinux_x86_64",
#    "cp39-manylinux_i686",
#    "cp310-manylinux_i686",
#    "cp311-manylinux_i686",
#    "cp312-manylinux_i686",
#    "pp39-manylinux_i686",
#    "pp310-manylinux_i686",
#    "cp39-musllinux_i686",
#]
